INSERT OR IGNORE INTO flights (pk, destination, price, company) VALUES (1, 'taiwan', 500, 'air taiwan');
INSERT OR IGNORE INTO flights (pk, destination, price, company) VALUES (2, 'thailand', 700, 'air asia');
INSERT OR IGNORE INTO flights (pk, destination, price, company) VALUES (3, 'california', 600, 'air america');
INSERT OR IGNORE INTO flights (pk, destination, price, company) VALUES (4, 'paris', 1200, 'air france');
INSERT OR IGNORE INTO flights (pk, destination, price, company) VALUES (5, 'paris', 990, 'air italia');
INSERT OR IGNORE INTO flights (pk, destination, price, company) VALUES (6, 'paris', 1080, 'lufthansa');
INSERT OR IGNORE INTO flights (pk, destination, price, company) VALUES (7, 'mauritius', 1190, 'air france');
INSERT OR IGNORE INTO flights (pk, destination, price, company) VALUES (8, 'mauritius', 1280, 'air mauritius');
INSERT OR IGNORE INTO flights (pk, destination, price, company) VALUES (9, 'mumbai', 599, 'air india');
INSERT OR IGNORE INTO flights (pk, destination, price, company) VALUES (10, 'toulouse', 889, 'air france');
INSERT OR IGNORE INTO flights (pk, destination, price, company) VALUES (11, 'lyon', 845, 'condor');
INSERT OR IGNORE INTO flights (pk, destination, price, company) VALUES (12, 'berlin', 709, 'lufthansa');
INSERT OR IGNORE INTO flights (pk, destination, price, company) VALUES (13, 'rome', 729, 'air italia');
INSERT OR IGNORE INTO flights (pk, destination, price, company) VALUES (14, 'rome', 699, 'air mauritius');
INSERT OR IGNORE INTO flights (pk, destination, price, company) VALUES (15, 'madrid', 689, 'air france');
INSERT OR IGNORE INTO flights (pk, destination, price, company) VALUES (16, 'johannesbourg', 529, 'air mauritius');
INSERT OR IGNORE INTO flights (pk, destination, price, company) VALUES (17, 'johannesbourg', 579, 'air africa');
INSERT OR IGNORE INTO flights (pk, destination, price, company) VALUES (18, 'antananarivo', 429, 'air madagascar');
INSERT OR IGNORE INTO flights (pk, destination, price, company) VALUES (19, 'antananarivo', 459, 'air austral');
INSERT OR IGNORE INTO flights (pk, destination, price, company) VALUES (20, 'new delhi', 629, 'air india');
INSERT OR IGNORE INTO flights (pk, destination, price, company) VALUES (21, 'new delhi', 639, 'air france');
INSERT OR IGNORE INTO flights (pk, destination, price, company) VALUES (22, 'newyork', 989, 'air america');
INSERT OR IGNORE INTO flights (pk, destination, price, company) VALUES (23, 'newyork', 889, 'air france');
INSERT OR IGNORE INTO flights (pk, destination, price, company) VALUES (24, 'newyork', 1029, 'air quatar');
INSERT OR IGNORE INTO flights (pk, destination, price, company) VALUES (25, 'atlanta', 1129, 'air america');
INSERT OR IGNORE INTO flights (pk, destination, price, company) VALUES (26, 'san francisco', 1129, 'air america');
INSERT OR IGNORE INTO flights (pk, destination, price, company) VALUES (27, 'san francisco', 1019, 'air quatar');
INSERT OR IGNORE INTO flights (pk, destination, price, company) VALUES (28, 'san francisco', 929, 'air france');
INSERT OR IGNORE INTO flights (pk, destination, price, company) VALUES (29, 'port louis', 1190, 'air france');
INSERT OR IGNORE INTO flights (pk, destination, price, company) VALUES (30, 'port louis', 1280, 'air mauritius');
